---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/configs":
    get:
      summary: Get an example of configuration object
      tags:
      - configs
      responses:
        '200':
          description: Returns default config values
  "/api/v1/payouts":
    post:
      summary: Receive a list of players to calculate paysheet
      tags:
      - Payouts
      parameters: []
      responses:
        '200':
          description: returns paysheet
        '400':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                jugadores:
                  type: array
                  items:
                    type: object
                    properties:
                      nombre:
                        type: string
                      nivel:
                        type: string
                      goles:
                        type: integer
                      sueldo:
                        type: number
                      bono:
                        type: number
                      sueldo_completo:
                        type: number
                      equipo:
                        type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: resuelve-challenge.herokuapp.com
